// Enum values mirror app/schemas/enums.py exactly. Wire values === Python names.

export const RISK_APPETITE = {
  CONSERVATIVE: "CONSERVATIVE",
  MODERATE: "MODERATE",
  AGGRESSIVE: "AGGRESSIVE",
} as const;
export type RiskAppetite = (typeof RISK_APPETITE)[keyof typeof RISK_APPETITE];

export const FINANCIAL_HEALTH = {
  EXCELLENT: "EXCELLENT",
  GOOD: "GOOD",
  FAIR: "FAIR",
  POOR: "POOR",
} as const;
export type FinancialHealth = (typeof FINANCIAL_HEALTH)[keyof typeof FINANCIAL_HEALTH];

export const PORTFOLIO_RISK = {
  CONSERVATIVE: "CONSERVATIVE",
  BALANCED: "BALANCED",
  GROWTH: "GROWTH",
  AGGRESSIVE: "AGGRESSIVE",
} as const;
export type PortfolioRisk = (typeof PORTFOLIO_RISK)[keyof typeof PORTFOLIO_RISK];

export const RISK_CLASS = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
} as const;
export type RiskClass = (typeof RISK_CLASS)[keyof typeof RISK_CLASS];

export const FINANCING_STRATEGY = {
  BORROW_100: "BORROW_100",
  BORROW_80_LIQUIDATE_20: "BORROW_80_LIQUIDATE_20",
  BORROW_60_LIQUIDATE_40: "BORROW_60_LIQUIDATE_40",
  BORROW_40_LIQUIDATE_60: "BORROW_40_LIQUIDATE_60",
  BORROW_20_LIQUIDATE_80: "BORROW_20_LIQUIDATE_80",
  LIQUIDATE_100: "LIQUIDATE_100",
} as const;
export type FinancingStrategy =
  (typeof FINANCING_STRATEGY)[keyof typeof FINANCING_STRATEGY];

export const LOAN_PURPOSE = {
  HOME: "HOME",
  VEHICLE: "VEHICLE",
  EDUCATION: "EDUCATION",
  PERSONAL: "PERSONAL",
  BUSINESS: "BUSINESS",
  MEDICAL: "MEDICAL",
} as const;
export type LoanPurpose = (typeof LOAN_PURPOSE)[keyof typeof LOAN_PURPOSE];

export const ASSET_TYPE = {
  STOCKS: "STOCKS",
  MUTUAL_FUNDS: "MUTUAL_FUNDS",
  FIXED_DEPOSIT: "FIXED_DEPOSIT",
  BONDS: "BONDS",
  CASH: "CASH",
  CRYPTO: "CRYPTO",
} as const;
export type AssetType = (typeof ASSET_TYPE)[keyof typeof ASSET_TYPE];

export const EMPLOYMENT_TYPE = {
  SALARIED: "SALARIED",
  SELF_EMPLOYED: "SELF_EMPLOYED",
  CONTRACT: "CONTRACT",
  RETIRED: "RETIRED",
} as const;
export type EmploymentType =
  (typeof EMPLOYMENT_TYPE)[keyof typeof EMPLOYMENT_TYPE];

export const ELIGIBILITY_STATUS = {
  ELIGIBLE: "ELIGIBLE",
  INELIGIBLE: "INELIGIBLE",
} as const;
export type EligibilityStatus =
  (typeof ELIGIBILITY_STATUS)[keyof typeof ELIGIBILITY_STATUS];

export const RECOMMENDATION_STATUS = {
  RECOMMENDED: "RECOMMENDED",
  NO_ELIGIBLE_PRODUCTS: "NO_ELIGIBLE_PRODUCTS",
  NO_FEASIBLE_CANDIDATES: "NO_FEASIBLE_CANDIDATES",
  ALL_CANDIDATES_BLOCKED: "ALL_CANDIDATES_BLOCKED",
  NO_SUITABLE_LOAN: "NO_SUITABLE_LOAN",
} as const;
export type RecommendationStatus =
  (typeof RECOMMENDATION_STATUS)[keyof typeof RECOMMENDATION_STATUS];

export const RECOMMENDATION_SOURCE = {
  ML_RANKER: "ML_RANKER",
  DETERMINISTIC_FALLBACK: "DETERMINISTIC_FALLBACK",
} as const;
export type RecommendationSource =
  (typeof RECOMMENDATION_SOURCE)[keyof typeof RECOMMENDATION_SOURCE];

export const CANDIDATE_OUTCOME = {
  RECOMMENDED: "RECOMMENDED",
  ELIGIBLE_UNSUITABLE: "ELIGIBLE_UNSUITABLE",
  INELIGIBLE: "INELIGIBLE",
  INFEASIBLE: "INFEASIBLE",
  GUARDRAIL_BLOCKED: "GUARDRAIL_BLOCKED",
  DOMINATED: "DOMINATED",
} as const;
export type CandidateOutcome =
  (typeof CANDIDATE_OUTCOME)[keyof typeof CANDIDATE_OUTCOME];

export const GROUNDING_OUTCOME = {
  GROUNDED: "GROUNDED",
  UNVERIFIED: "UNVERIFIED",
  UNGROUNDED: "UNGROUNDED",
} as const;
export type GroundingOutcome =
  (typeof GROUNDING_OUTCOME)[keyof typeof GROUNDING_OUTCOME];

export const EXPLANATION_SOURCE = {
  LLM: "LLM",
  TEMPLATE: "TEMPLATE",
} as const;
export type ExplanationSource =
  (typeof EXPLANATION_SOURCE)[keyof typeof EXPLANATION_SOURCE];

export const XAI_METHOD = {
  TREE_SHAP: "TREE_SHAP",
  FEATURE_IMPORTANCE: "FEATURE_IMPORTANCE",
} as const;
export type XaiMethod = (typeof XAI_METHOD)[keyof typeof XAI_METHOD];

export const GUARDRAIL_RULE = {
  MAX_DEBT_BURDEN_RATIO: "MAX_DEBT_BURDEN_RATIO",
  MAX_LOAN_TO_INCOME_MULTIPLE: "MAX_LOAN_TO_INCOME_MULTIPLE",
  MAX_LIQUIDATION_SHARE: "MAX_LIQUIDATION_SHARE",
  VOLATILE_ASSET_LIQUIDATION: "VOLATILE_ASSET_LIQUIDATION",
} as const;
export type GuardrailRule = (typeof GUARDRAIL_RULE)[keyof typeof GUARDRAIL_RULE];

export const MISMATCH_REASON_CODE = {
  CREDIT_SCORE_BELOW_MINIMUM: "CREDIT_SCORE_BELOW_MINIMUM",
  INCOME_BELOW_MINIMUM: "INCOME_BELOW_MINIMUM",
  AMOUNT_ABOVE_PRODUCT_MAX: "AMOUNT_ABOVE_PRODUCT_MAX",
  AMOUNT_BELOW_PRODUCT_MIN: "AMOUNT_BELOW_PRODUCT_MIN",
  TENURE_OUT_OF_RANGE: "TENURE_OUT_OF_RANGE",
  PURPOSE_NOT_SUPPORTED: "PURPOSE_NOT_SUPPORTED",
  EMI_EXCEEDS_AFFORDABILITY: "EMI_EXCEEDS_AFFORDABILITY",
  LIQUIDATION_EXCEEDS_PORTFOLIO: "LIQUIDATION_EXCEEDS_PORTFOLIO",
  REQUIRED_AMOUNT_UNREACHABLE: "REQUIRED_AMOUNT_UNREACHABLE",
  DEBT_BURDEN_CAP_EXCEEDED: "DEBT_BURDEN_CAP_EXCEEDED",
  LOAN_TO_INCOME_CAP_EXCEEDED: "LOAN_TO_INCOME_CAP_EXCEEDED",
  LIQUIDATION_SHARE_CAP_EXCEEDED: "LIQUIDATION_SHARE_CAP_EXCEEDED",
  VOLATILE_ASSET_LIQUIDATION_PROHIBITED: "VOLATILE_ASSET_LIQUIDATION_PROHIBITED",
  SUITABILITY_BELOW_THRESHOLD: "SUITABILITY_BELOW_THRESHOLD",
} as const;
export type MismatchReasonCode =
  (typeof MISMATCH_REASON_CODE)[keyof typeof MISMATCH_REASON_CODE];