"""
Synthetic dataset generation (P7).

ALL DATA PRODUCED HERE IS SYNTHETIC. No public credit dataset was available under
data/raw/, so customer financial profiles are generated, not sourced. Every file
carries a header comment saying so and a SYNTHETIC column on every row, so the fact
survives being opened in a spreadsheet, re-saved, or partially copied
(CONTEXT.md section 11).

These people do not exist. This is not banking history and must never be presented
as any.

OFFLINE ONLY. Lives in training/, never imported by app/. Run:

    python -m training.generate_data
"""

import csv
import random
from pathlib import Path

from app.schemas.enums import (
    AssetType,
    EmploymentType,
    FeedbackEventType,
    FinancingStrategy,
    LoanPurpose,
    RiskAppetite,
)

DATA_DIR = Path("data")
SEED = 20260902
N_CUSTOMERS = 400

# Share of customers deliberately generated with NO portfolio. The zero-portfolio
# path is first-class (CONTEXT.md non-negotiable 16), so it must be well represented
# in training, not a rare edge case the model never learns.
NO_PORTFOLIO_SHARE = 0.30

# Share of customers given seed interaction history. The rest are cold-start, which
# is likewise a first-class path.
WITH_HISTORY_SHARE = 0.40

SYNTHETIC_HEADER = (
    "# SYNTHETIC DATA — generated by training/generate_data.py. These customers, "
    "portfolios, products and interactions are fabricated. Not real banking data."
)


# ---------------------------------------------------------------- catalogue

# 14 products spanning six purposes, seven lenders and three credit tiers. Rates and
# limits are plausible for the Indian retail market but are invented.
PRODUCTS = [
    # product_id, lender, name, purposes, rate, min_amt, max_amt, min_ten, max_ten, min_cs, min_inc, fee
    ("HL-101", "Meridian Bank", "Meridian Home Advantage", [LoanPurpose.HOME], 8.35, 500_000, 15_000_000, 60, 240, 750, 70_000, 0.35),
    ("HL-102", "Kestrel Housing Finance", "Kestrel FlexiHome", [LoanPurpose.HOME], 9.10, 300_000, 8_000_000, 60, 240, 700, 45_000, 0.50),
    ("HL-103", "Sundial Credit Union", "Sundial First Home", [LoanPurpose.HOME], 10.25, 250_000, 5_000_000, 36, 180, 640, 28_000, 1.00),
    ("VL-201", "Meridian Bank", "Meridian Auto Prime", [LoanPurpose.VEHICLE], 9.40, 150_000, 3_500_000, 12, 84, 740, 50_000, 0.50),
    ("VL-202", "Harbourline Finance", "Harbourline Drive", [LoanPurpose.VEHICLE], 11.75, 80_000, 1_800_000, 12, 60, 660, 25_000, 1.25),
    ("EL-301", "Kestrel Housing Finance", "Kestrel Scholar", [LoanPurpose.EDUCATION], 8.75, 200_000, 6_000_000, 24, 144, 680, 30_000, 0.25),
    ("EL-302", "Sundial Credit Union", "Sundial Study Support", [LoanPurpose.EDUCATION], 10.50, 100_000, 2_500_000, 24, 120, 620, 20_000, 0.75),
    ("PL-401", "Anvil Credit", "Anvil Personal Prime", [LoanPurpose.PERSONAL, LoanPurpose.MEDICAL], 12.90, 100_000, 2_000_000, 12, 60, 720, 45_000, 1.50),
    ("PL-402", "Cobalt Money", "Cobalt Flexi Personal", [LoanPurpose.PERSONAL], 15.50, 50_000, 1_200_000, 12, 48, 660, 25_000, 2.25),
    ("PL-403", "Harbourline Finance", "Harbourline Everyday", [LoanPurpose.PERSONAL, LoanPurpose.MEDICAL], 17.90, 40_000, 700_000, 12, 36, 600, 18_000, 2.75),
    ("ML-501", "Sundial Credit Union", "Sundial Care", [LoanPurpose.MEDICAL], 11.25, 60_000, 1_500_000, 12, 60, 640, 22_000, 0.75),
    ("BL-601", "Anvil Credit", "Anvil Business Growth", [LoanPurpose.BUSINESS], 13.25, 500_000, 9_000_000, 24, 120, 740, 85_000, 1.25),
    ("BL-602", "Ironvale Capital", "Ironvale Trade Line", [LoanPurpose.BUSINESS], 15.75, 250_000, 4_000_000, 12, 84, 690, 55_000, 2.00),
    ("BL-603", "Cobalt Money", "Cobalt Seed Working Capital", [LoanPurpose.BUSINESS], 18.50, 100_000, 1_500_000, 12, 48, 630, 30_000, 2.50),
]

# Per-purpose requirement shape: (min multiple of annual income, max multiple,
# plausible tenures). Tenures are chosen to overlap the catalogue's own limits for
# that purpose, so eligibility failures reflect the customer, not the draw.
REQUIREMENT_SHAPE = {
    LoanPurpose.HOME: (1.0, 4.5, [60, 84, 120, 180, 240]),
    LoanPurpose.VEHICLE: (0.25, 1.4, [12, 24, 36, 48, 60, 84]),
    LoanPurpose.EDUCATION: (0.4, 2.2, [24, 36, 48, 60, 84, 120]),
    LoanPurpose.PERSONAL: (0.15, 0.9, [12, 24, 36, 48]),
    LoanPurpose.MEDICAL: (0.10, 0.7, [12, 24, 36, 48, 60]),
    LoanPurpose.BUSINESS: (0.4, 2.5, [24, 36, 48, 60, 84, 120]),
}

# Portfolio archetypes: (weights per asset type, relative size in months of income).
# Deliberately varied so the population is not dominated by one shape — including a
# volatile-heavy archetype, without which the volatile-liquidation guardrail is
# unreachable in practice (P6 finding).
PORTFOLIO_ARCHETYPES = {
    "cash_heavy": {AssetType.CASH: 0.55, AssetType.FIXED_DEPOSIT: 0.35, AssetType.MUTUAL_FUNDS: 0.10},
    "balanced": {AssetType.CASH: 0.15, AssetType.FIXED_DEPOSIT: 0.25, AssetType.MUTUAL_FUNDS: 0.30, AssetType.STOCKS: 0.20, AssetType.BONDS: 0.10},
    "equity_tilted": {AssetType.CASH: 0.08, AssetType.MUTUAL_FUNDS: 0.32, AssetType.STOCKS: 0.50, AssetType.BONDS: 0.10},
    "volatile_heavy": {AssetType.CASH: 0.05, AssetType.STOCKS: 0.55, AssetType.CRYPTO: 0.40},
    "conservative_income": {AssetType.FIXED_DEPOSIT: 0.45, AssetType.BONDS: 0.40, AssetType.CASH: 0.15},
}


def _write(path: Path, header: list[str], rows: list[list]) -> None:
    """
    Write a CSV with a leading comment line, then the header, then rows.

    READERS MUST SKIP LINES BEGINNING WITH '#'. The comment is deliberate: a file
    that loses its provenance when someone opens it is a file that will eventually be
    mistaken for real data.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        handle.write(SYNTHETIC_HEADER + "\n")
        writer = csv.writer(handle)
        writer.writerow(header)
        writer.writerows(rows)


def generate_products() -> list[list]:
    return [
        [
            product_id,
            lender,
            name,
            "|".join(p.value for p in purposes),
            rate,
            min_amount,
            max_amount,
            min_tenure,
            max_tenure,
            min_credit_score,
            min_income,
            fee,
            "TRUE",
        ]
        for (
            product_id,
            lender,
            name,
            purposes,
            rate,
            min_amount,
            max_amount,
            min_tenure,
            max_tenure,
            min_credit_score,
            min_income,
            fee,
        ) in PRODUCTS
    ]


def generate_customers(rng: random.Random) -> list[list]:
    """
    Customers spread across income bands, credit tiers and appetites.

    The spread is deliberately wide, including customers who will turn out to have no
    good option. A population where everyone has a suitable loan cannot teach the
    model that some profiles do not (CONTEXT.md section 7).
    """
    rows = []
    for index in range(N_CUSTOMERS):
        user_id = f"syn-{index:04d}"

        # Log-uniform income, so the population is not concentrated in one band and
        # scale-dependent bugs in the policy have room to show.
        income = round(10 ** rng.uniform(4.3, 6.0), -2)  # ~20,000 to ~1,000,000
        # Outgoings leave a real but variable margin. The upper end still produces
        # customers with almost no headroom — those are the ones who legitimately have
        # no good option, and the dataset needs them.
        expenses = round(income * rng.uniform(0.25, 0.72), -2)
        existing_emi = round(income * rng.uniform(0.0, 0.18), -2)

        credit_score = int(min(900, max(300, rng.gauss(710, 85))))
        employment = rng.choice(list(EmploymentType))
        employment_years = round(abs(rng.gauss(6.0, 4.5)), 1)
        age = rng.randint(23, 62)
        dependents = rng.choice([0, 0, 1, 2, 2, 3])

        # Requirement and tenure are drawn PER PURPOSE. A uniform draw across all
        # purposes generated people asking for a 12-month home loan or eight times
        # their annual income for a medical bill, which no product serves — the
        # resulting attrition was an artifact of the generator, not a real signal
        # about the catalogue.
        purpose = rng.choice(list(LoanPurpose))
        low, high, tenures = REQUIREMENT_SHAPE[purpose]
        annual_income = income * 12
        required_amount = round(annual_income * rng.uniform(low, high), -3)
        preferred_tenure = rng.choice(tenures)
        appetite = rng.choice(list(RiskAppetite))

        rows.append(
            [
                user_id,
                income,
                expenses,
                existing_emi,
                credit_score,
                employment.value,
                employment_years,
                age,
                dependents,
                purpose.value,
                required_amount,
                preferred_tenure,
                appetite.value,
                "TRUE",
            ]
        )
    return rows


def generate_portfolios(rng: random.Random, customer_ids: list[str]) -> list[list]:
    """
    One row per holding. Customers with no portfolio simply have no rows — the
    zero-portfolio path is an absence, not a row of zeros.
    """
    rows = []
    for user_id in customer_ids:
        if rng.random() < NO_PORTFOLIO_SHARE:
            continue
        archetype_name = rng.choice(list(PORTFOLIO_ARCHETYPES))
        weights = PORTFOLIO_ARCHETYPES[archetype_name]
        # Portfolio size as a multiple of monthly income is set by the caller's rng
        # draw here; absolute size is irrelevant to the policy, which is all ratios.
        total_value = round(10 ** rng.uniform(4.7, 7.2), -2)
        for asset_type, weight in weights.items():
            current = round(total_value * weight, 2)
            if current <= 0:
                continue
            # Gains and losses both occur, so unrealized_gain_loss is not one-signed.
            invested = round(current / rng.uniform(0.65, 1.45), 2)
            rows.append(
                [user_id, archetype_name, asset_type.value, current, invested, "TRUE"]
            )
    return rows


def generate_history(rng: random.Random, customer_ids: list[str]) -> list[list]:
    """
    Seed interaction history for a subset. The rest are cold-start, which the
    personalization layer treats as a first-class path.
    """
    rows = []
    product_ids = [p[0] for p in PRODUCTS]
    for user_id in customer_ids:
        if rng.random() >= WITH_HISTORY_SHARE:
            continue
        sessions = rng.randint(1, 5)
        for _ in range(sessions):
            product_id = rng.choice(product_ids)
            purpose = rng.choice(list(LoanPurpose))
            days_ago = round(rng.uniform(1, 540), 1)
            tenure = rng.choice([12, 24, 36, 48, 60, 84, 120])
            strategy = rng.choice(list(FinancingStrategy))
            rows.append(
                [
                    user_id,
                    "RECOMMENDATION",
                    days_ago,
                    product_id,
                    purpose.value,
                    round(10 ** rng.uniform(5.0, 6.8), -2),
                    tenure,
                    strategy.value,
                    round(rng.uniform(0.3, 0.95), 3),
                    "RECOMMENDED",
                    "",
                    "TRUE",
                ]
            )
            event = rng.choices(
                list(FeedbackEventType), weights=[0.5, 0.25, 0.25], k=1
            )[0]
            rows.append(
                [
                    user_id,
                    "EVENT",
                    max(0.1, days_ago - rng.uniform(0.0, 1.0)),
                    product_id,
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    event.value,
                    "TRUE",
                ]
            )
    return rows


def main() -> None:
    rng = random.Random(SEED)

    _write(
        DATA_DIR / "loan_products.csv",
        [
            "product_id",
            "lender",
            "product_name",
            "purposes",
            "annual_rate",
            "min_amount",
            "max_amount",
            "min_tenure_months",
            "max_tenure_months",
            "min_credit_score",
            "min_monthly_income",
            "processing_fee_pct",
            "SYNTHETIC",
        ],
        generate_products(),
    )

    customers = generate_customers(rng)
    _write(
        DATA_DIR / "customers.csv",
        [
            "user_id",
            "monthly_income",
            "monthly_expenses",
            "existing_emi",
            "credit_score",
            "employment_type",
            "employment_years",
            "age",
            "dependents",
            "purpose",
            "required_amount",
            "preferred_tenure_months",
            "risk_appetite",
            "SYNTHETIC",
        ],
        customers,
    )

    customer_ids = [row[0] for row in customers]
    _write(
        DATA_DIR / "portfolios.csv",
        ["user_id", "archetype", "asset_type", "current_value", "invested_value", "SYNTHETIC"],
        generate_portfolios(rng, customer_ids),
    )
    _write(
        DATA_DIR / "history.csv",
        [
            "user_id",
            "record_type",
            "days_ago",
            "product_id",
            "purpose",
            "amount",
            "tenure",
            "strategy",
            "suitability",
            "status",
            "event_type",
            "SYNTHETIC",
        ],
        generate_history(rng, customer_ids),
    )

    print(f"seed={SEED}")
    print(f"loan_products.csv  {len(PRODUCTS)} products")
    print(f"customers.csv      {len(customers)} customers (ALL SYNTHETIC)")
    for name in ("portfolios.csv", "history.csv"):
        lines = (DATA_DIR / name).read_text(encoding="utf-8").splitlines()
        print(f"{name:18} {len(lines) - 2} rows")


if __name__ == "__main__":
    main()
